include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat these as warnings rather than errors for gradual adoption
    cancel_subscriptions: warning
    close_sinks: warning
  exclude:
    # Exclude generated files from analysis
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
    - 'lib/generated/**'

linter:
  rules:
    # ===== Core Style Rules =====
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    no_leading_underscores_for_local_identifiers: true

    # ===== Async Rules =====
    await_only_futures: true
    unawaited_futures: true
    discarded_futures: true

    # ===== Constructor Rules =====
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true

    # ===== Type Safety Rules =====
    avoid_dynamic_calls: true
    type_annotate_public_apis: true
    avoid_types_on_closure_parameters: false

    # ===== Code Quality Rules =====
    prefer_foreach: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_operators: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_redundant_argument_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_late: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_decorated_box: true

    # ===== Safety Rules =====
    cancel_subscriptions: true
    close_sinks: true
    always_put_required_named_parameters_first: true
    avoid_catching_errors: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    no_duplicate_case_values: true
    throw_in_finally: true
    use_build_context_synchronously: true

    # ===== Performance Rules =====
    avoid_function_literals_in_foreach_calls: true
    avoid_positional_boolean_parameters: true
    no_adjacent_strings_in_list: true
    prefer_collection_literals: true
    prefer_spread_collections: true
    prefer_if_null_operators: true
    prefer_conditional_assignment: true

    # ===== Flutter-specific Rules =====
    use_full_hex_values_for_flutter_colors: true
