include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat these as warnings rather than errors for gradual adoption
    cancel_subscriptions: warning
    close_sinks: warning

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    prefer_final_locals: true
    await_only_futures: true
    unawaited_futures: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_foreach: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_operators: true
    avoid_dynamic_calls: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    type_annotate_public_apis: true
    no_leading_underscores_for_local_identifiers: true
    # Additional rules for better code quality
    prefer_const_constructors_in_immutables: true
    avoid_redundant_argument_values: true
    cancel_subscriptions: true
    close_sinks: true
    use_key_in_widget_constructors: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_late: true
